name: Build Sherpa-ONNX Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sherpa-onnx
        uses: actions/checkout@v4
        with:
          repository: 'k2-fsa/sherpa-onnx'
          submodules: recursive

      - name: Run Build Script
        run: |
          export SHERPA_ONNX_ENABLE_NNAPI=ON
          export SHERPA_ONNX_ENABLE_BINARY=ON
          
          chmod +x ./build-android-arm64-v8a.sh
          ./build-android-arm64-v8a.sh

      - name: Upload .so Libraries and Executables
        uses: actions/upload-artifact@v4
        with:
          name: sherpa-onnx-arm64-v8a
          path: |
            build-android-arm64-v8a/install/lib/*
            build-android-arm64-v8a/install/bin/*
